GLOBAL_PRELOAD_PARAMETERS = {
    # heat template parameter values common to all heat template continaing these parameters
    "defaults" : {
        'key_name' : 'vfw_key${uuid}',
        "pub_key" : "${pub_key}",
        "repo_url_blob" : "https://nexus.onap.org/content/repositories/raw",
        "repo_url_artifacts" : "https://nexus.onap.org/content/repositories/releases",
        "demo_artifacts_version" : "${GLOBAL_INJECTED_ARTIFACTS_VERSION}",
        "onap_private_net_id" : "${GLOBAL_INJECTED_NETWORK}",
        "onap_private_subnet_id" : "${GLOBAL_INJECTED_NETWORK}",
        "onap_private_net_cidr" : "10.0.0.0/8",
        "dcae_collector_ip" : "${dcae_collector_ip}",
        "dcae_collector_port" : "8080",
        "public_net_id" : "${GLOBAL_INJECTED_PUBLIC_NET_ID}",
        "cloud_env" : "${GLOBAL_INJECTED_CLOUD_ENV}",
        "install_script_version" : "${GLOBAL_INJECTED_SCRIPT_VERSION}",
    },

    # ##
    # heat template parameter values for heat template instances created during Vnf-Orchestration test cases
    # ##
    "Vnf-Orchestration" : {
        "vfw_preload.template": {
            "unprotected_private_net_id" : "vofwl01_unprotected${hostid}",
            "unprotected_private_net_cidr" : "192.168.10.0/24",
            "protected_private_net_id" : "vofwl01_protected${hostid}",
            "protected_private_net_cidr" : "192.168.20.0/24",
            "vfw_private_ip_0" : "192.168.10.100",
            "vfw_private_ip_1" : "192.168.20.100",
            "vfw_private_ip_2" : "10.0.${ecompnet}.1",
            "vpg_private_ip_0" : "192.168.10.200",
            "vpg_private_ip_1" : "10.0.${ecompnet}.2",
            "vsn_private_ip_0" : "192.168.20.250",
            "vsn_private_ip_1" : "10.0.${ecompnet}.3",
            'vfw_name_0': '${generic_vnf_name}',
            'vpg_name_0':'vofwl01pgn${hostid}',
            "vfw_image_name" : "${GLOBAL_INJECTED_UBUNTU_1404_IMAGE}",
            "vfw_flavor_name" : "${GLOBAL_INJECTED_VM_FLAVOR}",
            'vsn_name_0':'vofwl01snk${hostid}'
        },
        "vfwsnk_preload.template": {
            "unprotected_private_net_id" : "vofwlsnk_unprotected${hostid}",
            "unprotected_private_subnet_id" : "vofwlsnk_unprotected_sub${hostid}",
            "unprotected_private_net_cidr" : "192.168.10.0/24",
            "protected_private_net_id" : "vofwlsnk_protected${hostid}",
            "protected_private_subnet_id" : "vofwlsnk_protected_sub${hostid}",
            "protected_private_net_cidr" : "192.168.20.0/24",
            "vfw_private_ip_0" : "192.168.10.100",
            "vfw_private_ip_1" : "192.168.20.100",
            "vfw_private_ip_2" : "10.0.${ecompnet}.101",
            "vpg_private_ip_0" : "192.168.10.200",
            "vsn_private_ip_0" : "192.168.20.250",
            "vsn_private_ip_1" : "10.0.${ecompnet}.102",
            'vfw_name_0':'${generic_vnf_name}',
            'vsn_name_0':'vofwl01snk${hostid}',
            "image_name" : "${GLOBAL_INJECTED_UBUNTU_1404_IMAGE}",
            "flavor_name" : "${GLOBAL_INJECTED_VM_FLAVOR}",
        },
        "vpkg_preload.template": {
            "unprotected_private_net_id" : "vofwlsnk_unprotected${hostid}",
            "unprotected_private_subnet_id" : "vofwlsnk_unprotected_sub${hostid}",
            "unprotected_private_net_cidr" : "192.168.10.0/24",
            "protected_private_net_cidr" : "192.168.20.0/24",
            "vfw_private_ip_0" : "192.168.10.100",
            "vpg_private_ip_0" : "192.168.10.200",
            "vpg_private_ip_1" : "10.0.${ecompnet}.103",
            "vsn_private_ip_0" : "192.168.20.250",
            'vpg_name_0':'vofwl01pgn${hostid}',
            "image_name" : "${GLOBAL_INJECTED_UBUNTU_1404_IMAGE}",
            "flavor_name" : "${GLOBAL_INJECTED_VM_FLAVOR}",
        },
        "vlb_preload.template" : {
            "vlb_image_name" : "${GLOBAL_INJECTED_UBUNTU_1604_IMAGE}",
            "vlb_flavor_name" : "${GLOBAL_INJECTED_VM_FLAVOR}",
            "vlb_private_net_id" : "volb01_private${hostid}",
            "pktgen_private_net_id" : "volb01_pktgen${hostid}",
            "vlb_private_net_cidr" : "192.168.30.0/24",
            "vlb_private_ip_0" : "192.168.30.100",
            "vlb_private_ip_1" : "10.0.${ecompnet}.4",
            "vdns_private_ip_0" : "192.168.30.110",
            "vdns_private_ip_1" : "10.0.${ecompnet}.5",
            'vlb_name_0':'vovlblb${hostid}',
            'vdns_name_0':'vovlbdns${hostid}',
            "pktgen_private_net_cidr" : "192.168.9.0/24",
            "vpg_private_ip_1" : "10.0.${ecompnet}.7",
            "pg_int" : "192.168.9.109",
            "vpg_private_ip_0" : "192.168.9.110",
            "vlb_private_ip_2" : "192.168.9.111",
            "vip" : "192.168.9.112",
            "gre_ipaddr" : "192.168.30.112",
            "vpg_name_0" : "vovlbpgn${hostid}",
            "vnf_id" : "vLoadBalancer_${hostid}",
            "vf_module_id" : "vLoadBalancer"

        },
        "dnsscaling_preload.template" : {
            "vlb_private_net_id" : "volb01_private${hostid}",
            "vlb_private_ip_0" : "192.168.30.100",
            "vlb_private_ip_1" : "10.0.${ecompnet}.4",
            "vdns_private_ip_0" : "192.168.30.222",
            "vdns_private_ip_1" : "10.0.${ecompnet}.6",
            'scaling_vdns_name_0':'vovlbscaling${hostid}',
            "vlb_private_net_cidr" : "192.168.10.0/24"
        },
        "vims_preload.template" : {
            "bono_image_name" : "${GLOBAL_INJECTED_UBUNTU_1404_IMAGE}",
            "sprout_image_name" : "${GLOBAL_INJECTED_UBUNTU_1404_IMAGE}",
            "homer_image_name" : "${GLOBAL_INJECTED_UBUNTU_1404_IMAGE}",
            "homestead_image_name" : "${GLOBAL_INJECTED_UBUNTU_1404_IMAGE}",
            "ralf_image_name" : "${GLOBAL_INJECTED_UBUNTU_1404_IMAGE}",
            "ellis_image_name" : "${GLOBAL_INJECTED_UBUNTU_1404_IMAGE}",
            "dns_image_name" : "${GLOBAL_INJECTED_UBUNTU_1404_IMAGE}",
            "bono_flavor_name" : "${GLOBAL_INJECTED_VM_FLAVOR}",
            "sprout_flavor_name" : "${GLOBAL_INJECTED_VM_FLAVOR}",
            "homer_flavor_name" : "${GLOBAL_INJECTED_VM_FLAVOR}",
            "homestead_flavor_name" : "${GLOBAL_INJECTED_VM_FLAVOR}",
            "ralf_flavor_name" : "${GLOBAL_INJECTED_VM_FLAVOR}",
            "ellis_flavor_name" : "${GLOBAL_INJECTED_VM_FLAVOR}",
            "dns_flavor_name" : "${GLOBAL_INJECTED_VM_FLAVOR}",
            "repo_url" : "http://repo.cw-ngv.com/stable",
            "zone" : "me.cw-ngv.com",
            "dn_range_start" : "2425550000",
            "dn_range_length" : "10000",
            "dnssec_key" : "9FPdYTWhk5+LbhrqtTPQKw=="

        },
        "vvg_preload.template" : {
        }
    },
    # heat template parameter values for heat template instances created during Closed-Loop test cases
    "Closed-Loop" : {
        "vfw_preload.template": {
            "unprotected_private_net_id" : "clfwl01_unprotected${hostid}",
            "unprotected_private_net_cidr" : "192.168.110.0/24",
            "protected_private_net_id" : "clfwl01_protected${hostid}",
            "protected_private_net_cidr" : "192.168.120.0/24",
            "vfw_private_ip_0" : "192.168.110.100",
            "vfw_private_ip_1" : "192.168.120.100",
            "vfw_private_ip_2" : "10.0.${ecompnet}.11",
            "vpg_private_ip_0" : "192.168.110.200",
            "vpg_private_ip_1" : "10.0.${ecompnet}.12",
            "vsn_private_ip_0" : "192.168.120.250",
            "vsn_private_ip_1" : "10.0.${ecompnet}.13",
            'vfw_name_0':'${generic_vnf_name}',
            'vpg_name_0':'clfwl01pgn${hostid}',
            "vfw_image_name" : "${GLOBAL_INJECTED_UBUNTU_1404_IMAGE}",
            "vfw_flavor_name" : "${GLOBAL_INJECTED_VM_FLAVOR}",
            'vsn_name_0':'clfwl01snk${hostid}'
        },
        "vfwsnk_preload.template": {
            "unprotected_private_net_id" : "clfwlsnk_unprotected${hostid}",
            "unprotected_private_subnet_id" : "clfwlsnk_unprotected_sub${hostid}",
            "unprotected_private_net_cidr" : "192.168.10.0/24",
            "protected_private_net_id" : "clfwlsnk_protected${hostid}",
            "protected_private_subnet_id" : "clfwlsnk_protected_sub${hostid}",
            "protected_private_net_cidr" : "192.168.20.0/24",
            "vfw_private_ip_0" : "192.168.10.100",
            "vfw_private_ip_1" : "192.168.20.100",
            "vfw_private_ip_2" : "10.0.${ecompnet}.111",
            "vpg_private_ip_0" : "192.168.10.200",
            "vsn_private_ip_0" : "192.168.20.250",
            "vsn_private_ip_1" : "10.0.${ecompnet}.112",
            'vfw_name_0':'${generic_vnf_name}',
            'vsn_name_0':'clfwl01snk${hostid}',
            "image_name" : "${GLOBAL_INJECTED_UBUNTU_1404_IMAGE}",
            "flavor_name" : "${GLOBAL_INJECTED_VM_FLAVOR}",
        },
        "vpkg_preload.template": {
            "unprotected_private_net_id" : "clfwlsnk_unprotected${hostid}",
            "unprotected_private_subnet_id" : "clfwlsnk_unprotected_sub${hostid}",
            "unprotected_private_net_cidr" : "192.168.10.0/24",
            "protected_private_net_cidr" : "192.168.20.0/24",
            "vfw_private_ip_0" : "192.168.10.100",
            "vpg_private_ip_0" : "192.168.10.200",
            "vpg_private_ip_1" : "10.0.${ecompnet}.113",
            "vsn_private_ip_0" : "192.168.20.250",
            'vpg_name_0':'clfwl01pgn${hostid}',
            "image_name" : "${GLOBAL_INJECTED_UBUNTU_1404_IMAGE}",
            "flavor_name" : "${GLOBAL_INJECTED_VM_FLAVOR}",
        },
        "vlb_preload.template" : {
            "vlb_image_name" : "${GLOBAL_INJECTED_UBUNTU_1604_IMAGE}",
            "vlb_flavor_name" : "${GLOBAL_INJECTED_VM_FLAVOR}",
            "vlb_private_net_id" : "cllb01_private${hostid}",
            "pktgen_private_net_id" : "cllb01_pktgen${hostid}",
            "vlb_private_net_cidr" : "192.168.30.0/24",
            "vlb_private_ip_0" : "192.168.30.100",
            "vlb_private_ip_1" : "10.0.${ecompnet}.14",
            "vdns_private_ip_0" : "192.168.30.110",
            "vdns_private_ip_1" : "10.0.${ecompnet}.15",
            'vlb_name_0':'clvlblb${hostid}',
            'vdns_name_0':'clvlbdns${hostid}',
            "pktgen_private_net_cidr" : "192.168.9.0/24",
            "vpg_private_ip_1" : "10.0.${ecompnet}.17",
            "pg_int" : "192.168.9.109",
            "vpg_private_ip_0" : "192.168.9.110",
            "vlb_private_ip_2" : "192.168.9.111",
            "vip" : "192.168.9.112",
            "gre_ipaddr" : "192.168.30.112",
            "vpg_name_0" : "clvlbpgn${hostid}",
            "vnf_id" : "vLoadBalancer_${hostid}",
            "vf_module_id" : "vLoadBalancer"
        },
        "dnsscaling_preload.template" : {
            "vlb_image_name" : "${GLOBAL_INJECTED_UBUNTU_1604_IMAGE}",
            "vlb_flavor_name" : "${GLOBAL_INJECTED_VM_FLAVOR}",
            "vlb_private_net_id" : "cllb01_private${hostid}",
            "vlb_private_net_cidr" : "192.168.30.0/24",
            "vlb_private_ip_0" : "192.168.30.100",
            "vlb_private_ip_1" : "10.0.${ecompnet}.14",
            "vdns_private_ip_0" : "192.168.30.110",
            "vdns_private_ip_1" : "10.0.${ecompnet}.15",
            'vdns_name_0':'clvlbdns${hostid}',
            "vnf_id" : "vLoadBalancer_${hostid}",
            "vf_module_id" : "vLoadBalancer"
        },
        "vims_preload.template" : {
            "bono_image_name" : "${GLOBAL_INJECTED_UBUNTU_1404_IMAGE}",
            "sprout_image_name" : "${GLOBAL_INJECTED_UBUNTU_1404_IMAGE}",
            "homer_image_name" : "${GLOBAL_INJECTED_UBUNTU_1404_IMAGE}",
            "homestead_image_name" : "${GLOBAL_INJECTED_UBUNTU_1404_IMAGE}",
            "ralf_image_name" : "${GLOBAL_INJECTED_UBUNTU_1404_IMAGE}",
            "ellis_image_name" : "${GLOBAL_INJECTED_UBUNTU_1404_IMAGE}",
            "dns_image_name" : "${GLOBAL_INJECTED_UBUNTU_1404_IMAGE}",
            "bono_flavor_name" : "${GLOBAL_INJECTED_VM_FLAVOR}",
            "sprout_flavor_name" : "${GLOBAL_INJECTED_VM_FLAVOR}",
            "homer_flavor_name" : "${GLOBAL_INJECTED_VM_FLAVOR}",
            "homestead_flavor_name" : "${GLOBAL_INJECTED_VM_FLAVOR}",
            "ralf_flavor_name" : "${GLOBAL_INJECTED_VM_FLAVOR}",
            "ellis_flavor_name" : "${GLOBAL_INJECTED_VM_FLAVOR}",
            "dns_flavor_name" : "${GLOBAL_INJECTED_VM_FLAVOR}",
            "repo_url" : "http://repo.cw-ngv.com/stable",
            "zone" : "me.cw-ngv.com",
            "dn_range_start" : "2425550000",
            "dn_range_length" : "10000",
            "dnssec_key" : "9FPdYTWhk5+LbhrqtTPQKw=="
        },
        "vvg_preload.template" : {
        }
    },
    # heat template parameter values for heat template instances created for hands on demo test case
    "Demo" : {
        "vfw_preload.template": {
            "unprotected_private_net_id" : "demofwl_unprotected",
            "unprotected_private_net_cidr" : "192.168.110.0/24",
            "protected_private_net_id" : "demofwl_protected",
            "protected_private_net_cidr" : "192.168.120.0/24",
            "vfw_private_ip_0" : "192.168.110.100",
            "vfw_private_ip_1" : "192.168.120.100",
            "vfw_private_ip_2" : "10.0.${ecompnet}.21",
            "vpg_private_ip_0" : "192.168.110.200",
            "vpg_private_ip_1" : "10.0.${ecompnet}.22",
            "vsn_private_ip_0" : "192.168.120.250",
            "vsn_private_ip_1" : "10.0.${ecompnet}.23",
            'vfw_name_0':'${generic_vnf_name}',
            'vpg_name_0':'demofwl01pgn',
            "vfw_image_name" : "${GLOBAL_INJECTED_UBUNTU_1404_IMAGE}",
            "vfw_flavor_name" : "${GLOBAL_INJECTED_VM_FLAVOR}",
            'vsn_name_0':'demofwl01snk'
        },
        "vfwsnk_preload.template": {
            "unprotected_private_net_id" : "demofwlsnk_unprotected${hostid}",
            "unprotected_private_subnet_id" : "demofwlsnk_unprotected_sub${hostid}",
            "unprotected_private_net_cidr" : "192.168.10.0/24",
            "protected_private_net_id" : "demofwlsnk_protected${hostid}",
            "protected_private_subnet_id" : "vofwlsnk_protected_sub${hostid}",
            "protected_private_net_cidr" : "192.168.20.0/24",
            "vfw_private_ip_0" : "192.168.10.100",
            "vfw_private_ip_1" : "192.168.20.100",
            "vfw_private_ip_2" : "10.0.${ecompnet}.121",
            "vpg_private_ip_0" : "192.168.10.200",
            "vsn_private_ip_0" : "192.168.20.250",
            "vsn_private_ip_1" : "10.0.${ecompnet}.122",
            'vfw_name_0':'${generic_vnf_name}',
            'vsn_name_0':'demofwl01snk${hostid}',
            "image_name" : "${GLOBAL_INJECTED_UBUNTU_1404_IMAGE}",
            "flavor_name" : "${GLOBAL_INJECTED_VM_FLAVOR}",
        },
        "vpkg_preload.template": {
            "unprotected_private_net_id" : "demofwlsnk_unprotected${hostid}",
            "unprotected_private_subnet_id" : "demofwlsnk_unprotected_sub${hostid}",
            "unprotected_private_net_cidr" : "192.168.10.0/24",
            "protected_private_net_cidr" : "192.168.20.0/24",
            "vfw_private_ip_0" : "192.168.10.100",
            "vpg_private_ip_0" : "192.168.10.200",
            "vpg_private_ip_1" : "10.0.${ecompnet}.123",
            "vsn_private_ip_0" : "192.168.20.250",
            'vpg_name_0':'demofwl01pgn${hostid}',
            "image_name" : "${GLOBAL_INJECTED_UBUNTU_1404_IMAGE}",
            "flavor_name" : "${GLOBAL_INJECTED_VM_FLAVOR}"
        },
        "vlb_preload.template" : {
            "vlb_image_name" : "${GLOBAL_INJECTED_UBUNTU_1604_IMAGE}",
            "vlb_flavor_name" : "${GLOBAL_INJECTED_VM_FLAVOR}",
            "vlb_private_net_id" : "demolb_private${hostid}",
            "pktgen_private_net_id" : "demolb_pktgen${hostid}",
            "vlb_private_net_cidr" : "192.168.30.0/24",
            "vlb_private_ip_0" : "192.168.30.100",
            "vlb_private_ip_1" : "10.0.${ecompnet}.24",
            "vdns_private_ip_0" : "192.168.30.110",
            "vdns_private_ip_1" : "10.0.${ecompnet}.25",
            'vlb_name_0':'demovlblb${hostid}',
            'vdns_name_0':'demovlbdns${hostid}',
            "pktgen_private_net_cidr" : "192.168.9.0/24",
            "vpg_private_ip_1" : "10.0.${ecompnet}.27",
            "pg_int" : "192.168.9.109",
            "vpg_private_ip_0" : "192.168.9.110",
            "vlb_private_ip_2" : "192.168.9.111",
            "vip" : "192.168.9.112",
            "gre_ipaddr" : "192.168.30.112",
            "vpg_name_0" : "clvlbpgn${hostid}",
            "vnf_id" : "vLoadBalancer_${hostid}",
            "vf_module_id" : "vLoadBalancer"
        },
        "dnsscaling_preload.template" : {
            "vlb_private_net_id" : "demolb_private${hostid}",
            "vlb_private_ip_0" : "192.168.130.100",
            "vlb_private_ip_1" : "10.0.${ecompnet}.24",
            "vdns_private_ip_0" : "192.168.130.222",
            "vdns_private_ip_1" : "10.0.${ecompnet}.26",
            'scaling_vdns_name_0':'demovlbscaling${hostid}',
            "vlb_private_net_cidr" : "192.168.10.0/24"
        },
        "vims_preload.template" : {
            "bono_image_name" : "${GLOBAL_INJECTED_UBUNTU_1404_IMAGE}",
            "sprout_image_name" : "${GLOBAL_INJECTED_UBUNTU_1404_IMAGE}",
            "homer_image_name" : "${GLOBAL_INJECTED_UBUNTU_1404_IMAGE}",
            "homestead_image_name" : "${GLOBAL_INJECTED_UBUNTU_1404_IMAGE}",
            "ralf_image_name" : "${GLOBAL_INJECTED_UBUNTU_1404_IMAGE}",
            "ellis_image_name" : "${GLOBAL_INJECTED_UBUNTU_1404_IMAGE}",
            "dns_image_name" : "${GLOBAL_INJECTED_UBUNTU_1404_IMAGE}",
            "bono_flavor_name" : "${GLOBAL_INJECTED_VM_FLAVOR}",
            "sprout_flavor_name" : "${GLOBAL_INJECTED_VM_FLAVOR}",
            "homer_flavor_name" : "${GLOBAL_INJECTED_VM_FLAVOR}",
            "homestead_flavor_name" : "${GLOBAL_INJECTED_VM_FLAVOR}",
            "ralf_flavor_name" : "${GLOBAL_INJECTED_VM_FLAVOR}",
            "ellis_flavor_name" : "${GLOBAL_INJECTED_VM_FLAVOR}",
            "dns_flavor_name" : "${GLOBAL_INJECTED_VM_FLAVOR}",
            "repo_url" : "http://repo.cw-ngv.com/stable",
            "zone" : "me.cw-ngv.com",
            "dn_range_start" : "2425550000",
            "dn_range_length" : "10000",
            "dnssec_key" : "9FPdYTWhk5+LbhrqtTPQKw=="
        },
        "azurevfwsnk_preload.template": {
            "public_net_id" : "private_vnet",
            "onap_private_subnet_id" : "private_vsubnet",
            "unprotected_private_net_cidr" : "172.23.0.0/24",
            "protected_private_net_cidr" : "172.23.1.0/24",
            "flavor_name" : "Standard_D2",
            "onap_private_net_cidr" : "172.23.3.0/24",
            "vfw_private_ip_0" : "172.23.0.150",
            "vfw_private_ip_1" : "172.23.1.50",
            "image_name" : "UbuntuServer",
            "vfw_private_ip_2" : "10.0.100.1",
            "vsn_private_ip_0" : "172.23.1.100",
            "vsn_private_ip_1" : "172.23.3.50",
            "vfw_name_0":"zdfw1fwl01vfw01",
            "pub_key":"ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQD5zrmH1dHgXbNwP2qbNVySScnFVcEP25HBd2VJu2PiJLDhwgHj44Lj9ZvLyRFCetqd8CAKnLV5qy37rwaCtlH/t8Qb36cUGPhegxpF2++uTY0b6K7Zb6hEMBNw3J1z+GU7OoVwZJhsNAw4t8/7WWmJA4Owo99TJkEKvhCYjBCLoC5sIvG/lJsaFIG8A5MjnBlwgSZ3FsUU+aY1KYZUztodkyv7laDMOinwSvJggKrCugsqZdVo5bhmcSFbqrZa/a/wgqeok+79W0/DLh5Tlf7By46ASDKGnFlwDshPu++I3KMU3eRz0rJLOKeIUCz7k80X0WJ6BrSS7l+IrpDXV1M5 ubuntu@aria",
            "vsn_name_0":"zdfw1fwl01vsinc01",
            "dcae_collector_ip":"127.0.0.1",
            "fw_azure_domain_name_label":"rfwtestapp",
            "fw_azure_domain_fqdn":"rfwtestapp.eastus.cloudapp.azure.com",
            "snc_azure_domain_name_label":"rsnctestapp",
            "snc_azure_domain_fqdn":"rsnctestapp.eastus.cloudapp.azure.com",
            "dcae_collector_port":"8080",
            "repo_url_blob":"http://azure-servervdnsscripts.eastus.cloudapp.azure.com:8001",
            "repo_url_artifacts":"https://nexus.onap.org/content/groups/public",
            "demo_artifacts_version":"1.1.1",
            "install_script_version" : "1.1.1",
	    "azure_storage_account": "azurerobot",
            "azure_resource_group_name":"vfw-demo-rg",
            "cloud_env" : "azure",
        },
        "azurevpkg_preload.template": {
            "flavor_name" : "Standard_D2",
            "image_name" : "UbuntuServer",
            "public_net_id" : "private_vnet",
            "onap_private_subnet_id" : "private_vsubnet",
            "unprotected_private_net_cidr" : "172.23.0.0/24",
            "protected_private_net_cidr" : "172.23.1.0/24",
            "vpg_name_0" : "zdfw1fwl01vpg01",
            "onap_private_net_cidr" : "172.23.3.0/24",
            "vfw_private_ip_0" : "172.23.0.150",
            "vfw_private_ip_1":"172.23.1.50",
            "pub_key":"ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQD5zrmH1dHgXbNwP2qbNVySScnFVcEP25HBd2VJu2PiJLDhwgHj44Lj9ZvLyRFCetqd8CAKnLV5qy37rwaCtlH/t8Qb36cUGPhegxpF2++uTY0b6K7Zb6hEMBNw3J1z+GU7OoVwZJhsNAw4t8/7WWmJA4Owo99TJkEKvhCYjBCLoC5sIvG/lJsaFIG8A5MjnBlwgSZ3FsUU+aY1KYZUztodkyv7laDMOinwSvJggKrCugsqZdVo5bhmcSFbqrZa/a/wgqeok+79W0/DLh5Tlf7By46ASDKGnFlwDshPu++I3KMU3eRz0rJLOKeIUCz7k80X0WJ6BrSS7l+IrpDXV1M5 ubuntu@aria",
            "vfw_private_ip_2":"10.0.100.1",
            "vpg_private_ip_1":"10.0.100.2",
            "vsn_private_ip_0":"172.23.1.100",
            "pg_azure_domain_name_label":"rpptestapp",
            "pg_azure_domain_fqdn":"rpptestapp.eastus.cloudapp.azure.com",
            "repo_url_blob":"http://azure-servervdnsscripts.eastus.cloudapp.azure.com:8001",
            "install_script_version":"1.1.1",
            "dcae_collector_ip":"127.0.0.1",
            "dcae_collector_port":"8080",
            "repo_url_artifacts":"https://nexus.onap.org/content/groups/public",
            "demo_artifacts_version":"1.1.1",
            "cloud_env" : "openstack",
	    "azure_storage_account": "azurerobot",
            "vpkg_unprotected_private_ip" : "172.23.0.50",
            "azure_resource_group_name":"vfw-demo-rg",
        },
        "azurevdns_preload.template": {
            "vdns_name_0": "zdfw1lb01dns01",
            "vlb_name_0": "zdfw1lb01lb01",
            "vpg_name_0": "zdfw1lb01pg01",
            "vlb_image_name": "ubuntu16-ecomp.qcow2",
            "vlb_flavor_name": "m1.medium",
            "vlb_private_net_id": "vlb_vdns_vsubnet",
            "pktgen_private_net_id": "vpg_vlb_vsubnet",
            "onap_private_subnet_id": "public_vsubnet",
            "vlb_private_net_cidr": "172.23.10.0/24",
            "pktgen_private_net_cidr": "172.23.9.0/24",
            "onap_private_net_cidr": "172.23.8.0/24",
            "pub_key": "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC+nbU5EGLqxaArpZYl5zzLCZaJf+U8ycmUNNHabgIBpngdv77cCVE7lT8ajs/Y6O4amUgAIXKPWcaYolhcV9IfLFY3Wt8LcKd97NSAaq5wlTFinsofC9L65MTqgK7vVQ6gvRWrekmHjeCgsfi20gQWmMKOXJhD+Mz4S0v9JHsWinY6xrxgzabFlDE0giasxFXQzBbmWtZwn9443NrpNkKA2phKjXQM6v7Pi9Th6gOUMPSVo8sxfYJ1WUkLI7Qxrcb+mfPQkHAJpTvxIot+cHdDY61l2QuIDbV4FFO4Cn3P3mFrrBnu99h1fxa8klmPDv7APcpbZoo/O7CyapQt78Jn",
            "lb_azure_domain_name_label": "rlbtestapp",
            "lb_azure_domain_fqdn": "rlbtestapp.eastus.cloudapp.azure.com",
            "dns_azure_domain_name_label": "rdnstestapp",
            "dns_azure_domain_fqdn": "rdnstestapp.eastus.cloudapp.azure.com",
            "pg_azure_domain_name_label": "rpgtestapp",
            "pg_azure_domain_fqdn": "rpgtestapp.eastus.cloudapp.azure.com",
            "azure_storage_account": "azurerobo",
            "vlb_private_ip_0": "172.23.10.111",
            "vlb_private_ip_1": "172.23.8.1",
            "vlb_private_ip_2": "172.23.9.111",
            "repo_url_blob": "http://azure-servervdnsscripts.eastus.cloudapp.azure.com:8001",
            "install_script_version": "1.1.1",
            "vdns_private_ip_0": "172.23.10.211",
            "vdns_private_ip_1": "172.22.8.3",
            "vpg_private_ip_0": "172.23.9.110",
            "vpg_private_ip_1": "172.23.8.2",
            "dcae_collector_ip": "127.0.0.1",
            "dcae_collector_port": "8080",
            "repo_url_artifacts": "https://nexus.onap.org/content/groups/staging",
            "demo_artifacts_version": "1.2.0",
            "azure_resource_group_name":"vlb-demo-rg",
            "cloud_env": "azure",
        },
        "vvg_preload.template" : {
        }
    }
}
